### ISSUE TITLE
Load and Save crashes the app on HL

### ISSUE THREAD

**Issue by reneschulte** [maluoi/StereoKit-PaintTutorial#3]
I'm exploring your StereoKit. Love your intermediate mode approach here. Reminds me of good ol' OpenGL times. 

Just tried the sample on an HL2 and got a crash when tapping Save or Load.

**Comment by maluoi** [comment]
This is resolved with StereoKit v0.3.2! Fix is in commit adfa240dc34381fb0a7f89454c3e2b380f889728
